[project]
name = "mezcal"
description = "Mezzanine Caching and Access Layer Web Application"
version = "1.1.0-dev"
dependencies = [
    "requests_jwtauth"
]

[project.scripts]
mezcal = "mezcal.server:run"
